name: Linux CMake Integration and Unit Test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  InstallMPI__Latest_GCC__CmakeCompilation__GoogleTest :
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - name: Install latest available gcc
      run: |
          sudo apt-get update
          sudo apt-get install gcc-10 g++-10
      shell: bash

    - name: Install MPI
      run: |
          sudo apt-get update
          sudo apt-get install mpi-default-bin mpi-default-dev
      shell: bash

    - uses: actions/checkout@v2
    - name: Configure with CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CC: gcc-10
        CXX: g++-10
      run: |
        export MPI_HOME=/home/${USER}/.openmpi
        cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_TESTING=YES

    - name: Download googletest and Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build $GITHUB_WORKSPACE/build --config $BUILD_TYPE
      env:
          CC: gcc-10
          CXX: g++-10

    - name: Run Tests
      working-directory: ${{github.workspace}}/build/tests
      shell: bash
      env:
          CC: gcc-10
          CXX: g++-10
      run: ctest -C $BUILD_TYPE -V
